### ISSUE TITLE
Better animations

### ISSUE THREAD

**Issue by ZarmDev** [ZarmDev/To-doz#2]
How to help:
-Clone project
-Go to styles.js
Play around with the PopupAnim() function and the two other functions after it

**Comment by Midknightsnack** [comment]
Hi! Is it okay if I work on this?
I'm still relatively new to working on open source projects but I'll try my best to help. I'd really appreciate it.

**Comment by ZarmDev** [comment]
Sorry for not seeing this comment, thanks for working on the project!

**Comment by ZarmDev** [comment]
I experimented with the sidebar and on my end it's kind of slow, is that also the case for you?

**Comment by Midknightsnack** [comment]
It works fine for me. I've been working on it with Windows 10 on Microsoft Edge on my laptop. 

Also is there another way to contact you? I'd personally prefer email and maybe you can put your email in the README file because messaging through Github doesn't seem optimal.

**Comment by ZarmDev** [comment]
I can only message through Github, sorry.
