### ISSUE TITLE
Improved UI

### ISSUE THREAD

**Issue by ZarmDev** [ZarmDev/To-doz#4]
Improve the UI:
-The topbar
-Add color palettes
-Make all buttons look better
-Make better settings (popup)
-Better icons?

Anyone with CSS knowledge can easily work on this.
To change the CSS, go to style.css

**Comment by Osman-J** [comment]
I'll take a look into this

**Comment by ZarmDev** [comment]
@Osman-J @LewSplenda If you make changes, make a pull request. Thanks for checking it out
